# Data
dataset_name: 'Cora'
num_old: 4


# Model architecture
model_name: 'GAT'
hidden_size: 16


# Training
pre_train_epochs: 200
# ncd_train_epochs: 600
ncd_train_epochs: 90

# optimizer: 'adam'
learning_rate: 0.01
weight_decay: 0.0005

rampup_length: 50
rampup_coefficient: 5.0
increment_coefficient: 0.01
lambda_proto: 1.0
w_kd: 10


# Output
print_every_epochs: 10
pre_train_log_dir: 'config/log_pre_train/'
ncd_train_log_dir: 'config/log_ncd_train/'

model_dir: './models/save/'
# warmup_model_name: 'warmup_gcn_cora'
# incd_model_name: 'incd_gcn_cora'