# Data
dataset_name: 'PubMed'
# data_dir: 'data/Planetoid'
num_old: 2


# Random seed
# seed: 42
# random_seed: 1234

# Model architecture
model_name: 'GCN'
hidden_size: 32


# Regularization
# dropout: 0.5
# feat_adj_dropout: 0.5
# gl_dropout: 0.5


# Training
pre_train_epochs: 90
# ncd_train_epochs: 600
ncd_train_epochs: 200

# optimizer: 'adam'
learning_rate: 0.01
weight_decay: 0.0005

rampup_length: 50
rampup_coefficient: 5.0
increment_coefficient: 0.01
lambda_proto: 1.0
w_kd: 10


# Output
print_every_epochs: 10
pre_train_log_dir: 'config/log_pre_train/'
ncd_train_log_dir: 'config/log_ncd_train/'

model_dir: './models/save/'
